import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/features/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#41646a",
        "primary-container": "#7da1a8",
        "primary-fixed": "#c4e9f1",
        "primary-fixed-dim": "#a8cdd4",
        "on-primary": "#ffffff",
        "on-primary-container": "#12383e",
        "on-primary-fixed": "#001f24",
        "on-primary-fixed-variant": "#284c52",
        "secondary": "#5b5f5e",
        "secondary-container": "#dde0de",
        "secondary-fixed": "#e0e3e1",
        "secondary-fixed-dim": "#c4c7c5",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#5f6362",
        "on-secondary-fixed": "#181c1b",
        "on-secondary-fixed-variant": "#434846",
        "tertiary": "#596060",
        "tertiary-container": "#959c9c",
        "tertiary-fixed": "#dde4e3",
        "tertiary-fixed-dim": "#c1c8c7",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#2d3434",
        "on-tertiary-fixed": "#161d1d",
        "on-tertiary-fixed-variant": "#414848",
        "surface": "#f8f9ff",
        "surface-bright": "#f8f9ff",
        "surface-dim": "#ccdbf2",
        "surface-tint": "#41646a",
        "surface-variant": "#d4e4fa",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eef4ff",
        "surface-container": "#e5efff",
        "surface-container-high": "#dbe9ff",
        "surface-container-highest": "#d4e4fa",
        "background": "#f8f9ff",
        "on-background": "#0d1c2d",
        "on-surface": "#0d1c2d",
        "on-surface-variant": "#414849",
        "outline": "#71787a",
        "outline-variant": "#c1c8c9",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        sans: ["var(--font-google-sans)", "Google Sans", "Open Sans", "Inter", "sans-serif"],
        display: ["var(--font-google-sans)", "Google Sans", "Open Sans", "sans-serif"],
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.375rem",
        "md": "0.5rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "2xl": "1.5rem",
        "full": "9999px",
      },
      spacing: {
        "section-gap": "48px",
        "stack-gap": "16px",
        "touch-target-min": "48px",
        "container-padding-desktop": "64px",
        "container-padding-mobile": "24px",
      },
    },
  },
  plugins: [],
};

export default config;
